title: Technology Consultant
author: BitsInMyBlood
email: admin@thisbit.net
description: > # this means to ignore newlines until "baseurl:"
  I suppose this is a description for a blog page.

# social links
twitter_username: @bitsinmyblood
github_username:  bitsinmyblood

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
